cloudfoundry/service-fabrik-boshrelease

- config/final.yml
- packages/bosh-helpers/spec
- packages/docker/spec
- packages/golang/spec
1. replaced "{}" with "[]" in packages/*/spec files
2. In config/final.yml file appended folder name to s3 bucket name <s3 bucket name>/<folder name> (Removed folder name parameter)
> Fixing bosh create release in bosh cli v2

- templates/properties.yml
Modifying properties.yml to use directors instead of old director node.
> Modifying properties to use directors

- jobs/service-fabrik-broker/spec
- jobs/service-fabrik-broker/templates/config/settings.yml.erb
- jobs/service-fabrik-scheduler/spec
- jobs/service-fabrik-scheduler/templates/config/settings.yml.erb
changes related to fix [#32](https://github.com/SAP/service-fabrik-broker/issues/32)
> Fix Issue #32 

- config/final.yml
* Changes are done in final.yml to support creation of bosh relase
Using bosh cli version2
* Appended folder name with bucket name
* Added signature version key
> Modifying final.yml to support bosh cli v2

- jobs/service-fabrik-broker/spec
- jobs/service-fabrik-broker/templates/config/settings.yml.erb
- jobs/service-fabrik-scheduler/spec
- jobs/service-fabrik-scheduler/templates/config/settings.yml.erb
> T9 scheduled update

- jobs/service-fabrik-broker/spec
Related to: https://github.com/cloudfoundry-incubator/service-fabrik-broker/issues/125
> Increasing timeout duration for service-fabrik-broker

- jobs/service-fabrik-broker/spec
- jobs/service-fabrik-broker/templates/config/settings.yml.erb
- jobs/service-fabrik-scheduler/templates/config/settings.yml.erb
Modified the code specify a set of http response codes instead of skipping all client errors.
> Modified the code to specify a list of http response codes to be skipped for riemann logging

- jobs/service-fabrik-broker/monit
> Fixing docker config in broker's monit to complement to bosh2 manifest changes

- jobs/service-fabrik-broker/spec
- jobs/service-fabrik-broker/templates/config/settings.yml.erb
- jobs/service-fabrik-report/monit
- jobs/service-fabrik-report/spec
- jobs/service-fabrik-report/templates/bin/job_properties.sh.erb
- jobs/service-fabrik-report/templates/bin/service-fabrik-report_ctl.erb
- jobs/service-fabrik-report/templates/config/circuit-breaker-config.yml.erb
- jobs/service-fabrik-report/templates/config/eventlog-config-report.yml.erb
- jobs/service-fabrik-report/templates/config/settings.yml.erb
- jobs/service-fabrik-report/templates/config/syslog_forwarding.conf.erb
- jobs/service-fabrik-scheduler/templates/config/settings.yml.erb
- templates/jobs.yml
> Add service-fabrik-report job

- templates/properties.yml
> Fixes #41 Refactored bootstrap bosh director name to bosh-sf

- jobs/service-fabrik-broker/templates/config/eventlog-config-external.yml.erb
- jobs/service-fabrik-scheduler/templates/config/eventlog-config-external.yml.erb
Closes #47 
Add schedule update operation in eventlog config
> Add schedule update in eventlog

- jobs/service-fabrik-broker/templates/config/settings.yml.erb
- jobs/service-fabrik-scheduler/spec
- jobs/service-fabrik-scheduler/templates/config/settings.yml.erb
Fixes bug - https://github.com/cloudfoundry-incubator/service-fabrik-boshrelease/issues/53
> Fix the config used for should_start_after_hr

- templates/deployment.yml
Description: Passing virtual-host provider params in the deployment file
> Fixes #50: Service-fabrik boshrelease deployment fails with provided template

- jobs/service-fabrik-broker/templates/config/eventlog-config-internal.yml.erb
- jobs/service-fabrik-scheduler/templates/config/eventlog-config-internal.yml.erb
* Changed the event logger paths
> Changing the broker path of event log internal

- jobs/service-fabrik-broker/templates/config/eventlog-config-internal.yml.erb
- jobs/service-fabrik-scheduler/templates/config/eventlog-config-internal.yml.erb
Fixes https://github.com/cloudfoundry-incubator/service-fabrik-broker/issues/237
> Adding http success codes for last operation poll for delete call

- templates/ops-file-boshlite.yml
- Remove reference to bootstrap-bosh in ops config arguments
- Format to form valid YAML on merge
> Make deployment work on Bosh-Lite

- templates/cloud-config-boshlite.yml
- templates/deployment.yml
- templates/ops-file-boshlite.yml
- Change "cf" to "routing" release for route-registrar
- Change path for services subnet
> Fix upload-release failure in Bosh-Lite

- jobs/service-fabrik-broker/spec
- jobs/service-fabrik-broker/templates/config/settings.yml.erb
* Added new property 'EnableSecurityGroupsOps' under feature for service-fabrik-broker.
* Corresponding changes in settings.yml.erb
> Added new feature EnableSecurityGroupsOps

- jobs/service-fabrik-broker/spec
Adding default props so as to not break the bosh release builds.
> added defaults for credhub settings as they are optional params

- config/blobs.yml
- packages/keepalived/packaging
- packages/keepalived/spec
The latest version provides fix for https://github.com/acassen/keepalived/issues/867 and https://github.com/acassen/keepalived/issues/864
> Bumping keepalived version to 2.0.5

- jobs/service-fabrik-backup-manager/templates/config/settings.yml.erb
- jobs/service-fabrik-broker/spec
- jobs/service-fabrik-broker/templates/config/settings.yml.erb
- jobs/service-fabrik-report/templates/config/settings.yml.erb
- jobs/service-fabrik-scheduler/templates/config/settings.yml.erb
- templates/deployment.yml
changes made to support PITR by SF broker
> Changes to support PITR

- templates/cloud-config-boshlite.yml
Updating working CC with boshlite.
> Update cloud config

- jobs/service-fabrik-backup-manager/spec
- jobs/service-fabrik-backup-manager/templates/config/eventlog-config-external.yml.erb
- Add event log config for backup manager
> Add event log config for backup manager

- jobs/service-fabrik-backup-manager/spec
- jobs/service-fabrik-backup-manager/templates/config/eventlog-config-external.yml.erb
Cherry pick for release branch https://github.com/cloudfoundry-incubator/service-fabrik-boshrelease/pull/117
> Restore mgr fix rel.08b

- README.md
Update the command to use `-d` parameter as it cannot be empty.
> Provide deployment parameter

- templates/apiserver.yml
removing webhook job from apiserver manifest for local development
> Remove webhook job

- README.md
- crds/backup.servicefabrik.io_v1alpha1_defaultbackups.yaml
- crds/backup.servicefabrik.io_v1alpha1_defaultrestores.yaml
- crds/bind.servicefabrik.io_v1alpha1_directorbinds.yaml
- crds/bind.servicefabrik.io_v1alpha1_dockerbinds.yaml
- crds/bind.servicefabrik.io_v1alpha1_virtualhostbinds.yaml
- crds/deployment.servicefabrik.io_v1alpha1_directors.yaml
- crds/deployment.servicefabrik.io_v1alpha1_dockers.yaml
- crds/deployment.servicefabrik.io_v1alpha1_virtualhosts.yaml
- crds/lock.servicefabrik.io_v1alpha1_deploymentlocks.yaml
- services/blueprint.yml.erb
- templates/deployment.yml
- templates/ops-file-boshlite-gcp.yml
- templates/ops-file-boshlite.yml
- templates/render
- Add crds
- backup.servicefabrik.io_v1alpha1_defaultbackups.yaml
- backup.servicefabrik.io_v1alpha1_defaultrestores.yaml
- bind.servicefabrik.io_v1alpha1_directorbinds.yaml
- bind.servicefabrik.io_v1alpha1_dockerbinds.yaml
- bind.servicefabrik.io_v1alpha1_virtualhostbinds.yaml
- deployment.servicefabrik.io_v1alpha1_directors.yaml
- deployment.servicefabrik.io_v1alpha1_dockers.yaml
- deployment.servicefabrik.io_v1alpha1_virtualhosts.yaml
- lock.servicefabrik.io_v1alpha1_deploymentlocks.yaml
- Update render script
- Add jobs
- service-fabrik-backup-manager
- service-fabrik-bosh-manager
- bpm
- service-fabrik-docker-manager
- service-fabrik-virtualhost-manager
- Add `ops-file-boshlite-gcp.yml`
- Update `ops-file-boshlite.yml`
> Update boshrelease to work with boshlite

- jobs/service-fabrik-bosh-manager/templates/config/settings.yml.erb
- jobs/service-fabrik-broker/spec
- jobs/service-fabrik-broker/templates/config/settings.yml.erb
- jobs/service-fabrik-docker-manager/templates/config/settings.yml.erb
- jobs/service-fabrik-scheduler/templates/config/settings.yml.erb
Reversing credhub changes from spec file and settings.yml.erb file.
> Reversing Credhub

- jobs/service-fabrik-bosh-manager/spec
- jobs/service-fabrik-bosh-manager/templates/config/eventlog-config-internal.yml.erb
- This config enables any event logging in bosh manager process.
- Code part of bosh manager process can write events.
> Added internal event log config for event logging in bosh manager

- jobs/service-fabrik-serviceflow-manager/templates/config/settings.yml.erb
Added 2 general missing prop required for service flow job.
> added missing prop required for service flow job

- crds/deployment.servicefabrik.io_v1alpha1_virtualhosts.yaml
- jobs/service-fabrik-backup-manager/templates/config/settings.yml.erb
- jobs/service-fabrik-bosh-manager/templates/config/settings.yml.erb
- jobs/service-fabrik-broker/spec
- jobs/service-fabrik-broker/templates/config/settings.yml.erb
- jobs/service-fabrik-docker-manager/templates/config/settings.yml.erb
- jobs/service-fabrik-report/templates/config/settings.yml.erb
- jobs/service-fabrik-scheduler/templates/config/settings.yml.erb
- jobs/service-fabrik-virtualhost-manager/templates/config/settings.yml.erb
- templates/deployment.yml
related to : https://github.com/cloudfoundry-incubator/service-fabrik-broker/pull/471
> removed virtualhost provider settings

- config/blobs.yml
- packages/apiserver/packaging
- packages/apiserver/spec
* adding new blob for 1.12.4 version
* changing the packaging and spec
> Upgrading APIServer

- templates/apiserver.yml
* Adding webhook job back with apiserver
* Current webhook job does defaulting of state in labels for all operator resources
> Adding webhook job back in the apiserver local

- jobs/service-fabrik-backup-manager/templates/config/eventlog-config-external.yml.erb
- jobs/service-fabrik-broker/templates/config/eventlog-config-external.yml.erb
- jobs/service-fabrik-scheduler/templates/config/eventlog-config-external.yml.erb
boshrelease changes regarding: [service-fabrik-broker/pull/552](https://github.com/cloudfoundry-incubator/service-fabrik-broker/pull/552).
> eventlog-config for cancel schedule_update API

- .travis.yml
- config/blobs.yml
* Changing bosh cli version as create release with older cli is failing
* removing older blobs of golang and apiserver
> Travis fix for interoperator

- jobs/service-fabrik-broker/spec
- jobs/webhooks/templates/config/bpm.yml.erb
Add property to set log level for webhooks
> Add webhook log level

- jobs/service-fabrik-broker/spec
- jobs/webhooks/spec
- jobs/webhooks/templates/config/bpm.yml.erb
Move property to webhook, in webhook job
> Move property to webhook

- jobs/docker/templates/bin/lvmvd_ctl.erb
- Made changes to explicit startup of  service group
- disabled the new lvmetad cache feature
> Support for xenial  for docker nodes

- jobs/docker/templates/bin/lvmvd_ctl.erb
fix to check and active service volume group
> activate Volume group

- jobs/keepalived/templates/bin/action.sh.erb
- jobs/keepalived/templates/config/keepalived.conf.erb
> Fix keepalived ARP cache

- jobs/service-fabrik-broker/templates/bin/health_check.erb
- Active Active setup for Service Fabrik
- Both Nodes sends positive health check message.
> Service Fabrik HA

- jobs/service-fabrik-interoperator/spec
- jobs/service-fabrik-interoperator/templates/bin/pre_start.erb
- jobs/service-fabrik-interoperator/templates/config/cluster.yaml.erb
- Create SFCluster with name "1"
- Create correponding secret with kubeconfig
Feature: HCPCFS-2378
Depends on https://github.com/cloudfoundry-incubator/service-fabrik-broker/pull/646 and https://github.infra.hana.ondemand.com/servicefabrik/interoperator-deployment-component/pull/32
> [interoperator] Cluster Registry Support

- jobs/service-fabrik-interoperator/templates/bin/pre_start.erb
- packages/interoperator/packaging
- packages/interoperator/pre_packaging
- Use go mod for interoperator
- Update CRD path
Broker PR: https://github.com/cloudfoundry-incubator/service-fabrik-broker/pull/744
> Interoperator kubebuilder 2.0 migration

- config/blobs.yml
- jobs/service-fabrik-interoperator/templates/bin/pre_start.erb
- packages/golang/spec
- packages/interoperator/packaging
- packages/interoperator/pre_packaging
- packages/interoperator/spec
- packages/lvmvd/packaging
- packages/node/spec
- packages/service-fabrik-broker/pre_packaging
- packages/service-fabrik-broker/spec
- packages/service-fabrik-deployment-hooks/pre_packaging
- packages/service-fabrik-deployment-hooks/spec
- packages/swarm/packaging
- packages/webhooks/packaging
- packages/webhooks/pre_packaging
- packages/webhooks/spec
- Update nodejs to v12.13.1 lts
- Update golang version to 1.13.5
- Install nodejs/golang during pre_packaging also if used
> Update Golang & Nodejs Version

- packages/interoperator/packaging
> Force go build to use vendor for dependencies

- jobs/service-fabrik-interoperator/templates/bin/pre_start.erb
Apply CRDs only on canary instance
Bug: NGPBUG-111161
> Fix binding controller stopping on upgrade

- jobs/service-fabrik-backup-manager/templates/bin/service-fabrik-backup-manager_ctl.erb
- jobs/service-fabrik-bosh-manager/templates/bin/service-fabrik-bosh-manager_ctl.erb
- jobs/service-fabrik-broker-ext/templates/bin/service-fabrik-broker-ext_ctl.erb
- jobs/service-fabrik-broker/templates/bin/service-fabrik-broker_ctl.erb
- jobs/service-fabrik-deployment-hooks/templates/bin/service-fabrik-deployment-hooks_ctl.erb
- jobs/service-fabrik-docker-manager/templates/bin/service-fabrik-docker-manager_ctl.erb
- jobs/service-fabrik-postgresqlmt-operator/templates/config/bpm.yml.erb
- jobs/service-fabrik-report/templates/bin/service-fabrik-report_ctl.erb
- jobs/service-fabrik-scheduler/templates/bin/service-fabrik-scheduler_ctl.erb
- jobs/service-fabrik-serviceflow-manager/templates/config/bpm.yml.erb
- jobs/service-fabrik-virtualhost-manager/templates/bin/service-fabrik-virtualhost-manager_ctl.erb
- packages/service-fabrik-broker/pre_packaging
- packages/service-fabrik-deployment-hooks/packaging
- packages/service-fabrik-deployment-hooks/pre_packaging
To adopt https://github.com/cloudfoundry-incubator/service-fabrik-broker/pull/823/
> adopting new directory structure of sf repo

- crds/backup.servicefabrik.io_v1alpha1_defaultbackups.yaml
- crds/backup.servicefabrik.io_v1alpha1_defaultrestores.yaml
- crds/bind.servicefabrik.io_v1alpha1_directorbinds.yaml
- crds/bind.servicefabrik.io_v1alpha1_dockerbinds.yaml
- crds/bind.servicefabrik.io_v1alpha1_postgresqlmtbinds.yaml
- crds/bind.servicefabrik.io_v1alpha1_virtualhostbinds.yaml
- crds/deployment.servicefabrik.io_v1alpha1_directors.yaml
- crds/deployment.servicefabrik.io_v1alpha1_dockers.yaml
- crds/deployment.servicefabrik.io_v1alpha1_postgresqlmts.yaml
- crds/deployment.servicefabrik.io_v1alpha1_virtualhosts.yaml
- crds/instance.servicefabrik.io_v1alpha1_sfevents.yaml
- crds/lock.servicefabrik.io_v1alpha1_deploymentlocks.yaml
- jobs/service-fabrik-admin-app/templates/config/settings.yml.erb
- jobs/service-fabrik-backup-manager/templates/config/settings.yml.erb
- jobs/service-fabrik-bosh-manager/templates/config/settings.yml.erb
- jobs/service-fabrik-broker-ext/templates/config/settings.yml.erb
- jobs/service-fabrik-broker/templates/config/settings.yml.erb
- jobs/service-fabrik-docker-manager/templates/config/settings.yml.erb
- jobs/service-fabrik-postgresqlmt-operator/spec
- jobs/service-fabrik-postgresqlmt-operator/templates/config/kubeconfig.yaml.erb
- jobs/service-fabrik-postgresqlmt-operator/templates/config/settings.yml.erb
- jobs/service-fabrik-quota-app/templates/config/settings.yml.erb
- jobs/service-fabrik-report/templates/config/settings.yml.erb
- jobs/service-fabrik-scheduler/templates/config/settings.yml.erb
- jobs/service-fabrik-serviceflow-manager/spec
- jobs/service-fabrik-serviceflow-manager/templates/config/kubeconfig.yaml.erb
- jobs/service-fabrik-serviceflow-manager/templates/config/settings.yml.erb
- jobs/service-fabrik-virtualhost-manager/templates/config/settings.yml.erb
Related to : cloudfoundry-incubator/service-fabrik-broker#913
Feature: HCPCFS-2737
> Use kubeconfig to connect to apiserver

- config/blobs.yml
- jobs/docker/templates/bin/lvmvd_ctl.erb
- packages/lvm2/packaging
- packages/lvm2/spec
Changes in the PR:
- Blobs for lvm2 dependencies
- Support for bionic in lvm2 packaging and ctl scripts
> changes for supporting lvm2 job with ubuntu bionic stemcell

- jobs/service-fabrik-broker/spec
- jobs/service-fabrik-broker/templates/config/settings.yml.erb
Companion for https://github.com/cloudfoundry-incubator/service-fabrik-broker/pull/1294
Feature HCPCFS-2938
> add send_binding_metadata property in spec

- config/blobs.yml
- packages/golang/spec
- packages/interoperator/spec
- packages/lvmvd/packaging
- packages/swarm/packaging
- packages/swarm/spec
- packages/webhooks/packaging
- packages/webhooks/spec
Updated golang libary to v 1.17.5 in packaging
> HCPCFS-3059 Updated golang libary to v 1.17.5 in packaging

- packages/webhooks/packaging
- packages/webhooks/pre_packaging
Updating webhooks packaging to go modules.
Related: cloudfoundry-incubator/service-fabrik-broker/pull/1571
> HCPCFS-3261 Updating webhooks packaging

- config/blobs.yml
- packages/golang/spec
- packages/interoperator/spec
- packages/node/spec
- packages/service-fabrik-broker/spec
- packages/service-fabrik-deployment-hooks/spec
- packages/webhooks/spec
This pull request updates Golang and Nodejs.
- Go to 1.19.3
- Nodejs to 14.21.2
> go and node version updated

- jobs/service-fabrik-admin-app/templates/config/settings.yml.erb
- jobs/service-fabrik-broker/spec
This reverts commit 3779b366c894feff4aa9ef57a4dbcb96c1f95e6f.
> Remove parameter mongodb.provision.previous_plan_id from settings

- config/blobs.yml
- packages/docker/packaging
- packages/docker/spec
This reverts commit fe05cc4ba1a9cced34214515880cd34827edd6e8.
> Revert "update docker binary used"
