- config/final.yml
This PR includes fix for issue: https://github.com/SAP/service-fabrik-boshrelease/issues/6
Blobstore error: Failed to create object, S3 response error code NoSuchKey: The specified key does not exist.
During final release call we were getting error.
```shell
Building packages
-----------------
Building golang...
Using final version '95c358c1eeabe9495e089de333e0c91eee2fef0c'
Uploading final version '95c358c1eeabe9495e089de333e0c91eee2fef0c'...
Uploaded, blobstore id '5924ebab-6dec-411b-86c5-8491e94064fc'
Building bosh-helpers...
Using final version 'e1bbff85fa1e4b1d51887ba6ecff6949ca92e8f6'
Uploading final version 'e1bbff85fa1e4b1d51887ba6ecff6949ca92e8f6'...
Uploaded, blobstore id 'ad205f16-f98a-4045-a609-74e9b341c3a9'
Building docker...
Using final version …
```
> [Fix bosh release --final] Putting folder name in separate parameter

- .travis.yml
Currently there are no validations in place for code contributions on service-fabrik-boshrelease.
This adds a .travis.yml file for validating code by creating a dev bosh release and attaching the run status on the PR page
> Added Travis validations for service-fabrik boshrelease

- jobs/service-fabrik-broker/templates/config/circuit-breaker-config.yml.erb
- jobs/service-fabrik-scheduler/templates/config/circuit-breaker-config.yml.erb
- templates/properties.yml
Description: This fix incorporate changes to circuit breaker config for
multiple bosh
With multiple bosh now we can have more than one directors. The
configuration files instead of having a static configuration now needs
to iterate over the complete array and subsequently add information on
all the directors.
Another change has been made into templates/properties.yml. Since this
properties file is specific to bosh-lite we should have only one single
bosh director.
> Closes-Bug: issues: #9

- config/blobs.yml
- jobs/docker/templates/bin/docker_ctl.erb
- packages/docker/packaging
- packages/docker/spec
Since docker demon itself creates  network bridge  there is no need to use additional package Bridge-Utils. The changes part of this changes list are related to removal of the bridge-utils references from bosh release
Changes made :
- docker packaging removed the packaging of  the bridge-Utils.
- Docker job startup script, removed the explicit creation of network bridge using bridge-utils.
- update blobs.yml (using "bosh remove-blob" command, which after removing the bridge-utils bosh cli reorganized the blob entries alphabetically)
>  Remove Bridge-utils package usagage in docker node

- jobs/swarm_manager/templates/bin/swarm_manager_ctl
During the startup of swarm process we restart the rsyslog, some times
rsyslogs start return non zero value which does not effect functionality of the
swarm process but checking its return value causes landscape deployment to fail.
Hence ignoring the rsyslog restart value.
> Closes-Bug: issues: Swarm process start is failing

- jobs/service-fabrik-broker/spec
- jobs/service-fabrik-broker/templates/config/settings.yml.erb
- jobs/service-fabrik-scheduler/spec
- jobs/service-fabrik-scheduler/templates/config/settings.yml.erb
- Added a new config in broker settings.yml which would be used to decide whether or not to skip sending events to Riemann in case the incoming request to broker was not processed due to HTTP client error - https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_errors
PR on the broker - https://github.com/SAP/service-fabrik-broker/pull/101
> Added configs used to support skipping of events to riemann in case of client errors.

- jobs/service-fabrik-broker/spec
- jobs/service-fabrik-broker/templates/config/settings.yml.erb
Issue: https://github.com/cloudfoundry-incubator/service-fabrik-boshrelease/issues/30
Raising this new PR to correct the [PR](https://github.com/cloudfoundry-incubator/service-fabrik-boshrelease/pull/29), adding new format in which properties are expected to be given in jobs spec, changed according to BOSH V2 changes.
This is tested in SC6 landscape with the latest code changes.
> corrected the virtual host provider properties to match new format

- config/blobs.yml
- jobs/service-fabrik-broker/spec
- jobs/service-fabrik-broker/templates/bin/drain.erb
- jobs/service-fabrik-broker/templates/bin/job_properties.sh.erb
- jobs/service-fabrik-broker/templates/config/settings.yml.erb
- jobs/service-fabrik-report/templates/config/settings.yml.erb
- jobs/service-fabrik-scheduler/spec
- jobs/service-fabrik-scheduler/templates/config/settings.yml.erb
- packages/yaml2json/packaging
- packages/yaml2json/spec
- src/bosh-helpers/ctl_setup.sh
1. Drain script added in sf bosh release which will update the progress of maintenance window with the broker update status, which can be used by scheduler to then decide if it wants to go into maintenance immediately or wait till broker update has started.
> improve scheduler availability

- jobs/service-fabrik-broker/templates/bin/service-fabrik-broker_ctl.erb
- jobs/service-fabrik-report/templates/bin/service-fabrik-report_ctl.erb
- jobs/service-fabrik-scheduler/templates/bin/service-fabrik-scheduler_ctl.erb
- packages/service-fabrik-broker/packaging
- packages/service-fabrik-broker/pre_packaging
- packages/service-fabrik-broker/spec
Change list of files in package `spec`
Copy only required files in `packaging` script
Travis build is failing because of outdated src `service-fabrik-broker`
> Modularize service-fabrik-broker source code

- jobs/service-fabrik-broker/spec
- jobs/service-fabrik-scheduler/templates/config/settings.yml.erb
The add on jobs that are added into a service manifest by service fabrik broker is configured via the param 'service_addon_jobs'. This property was defined from service fabrik broker which is why deployments post update does not show as outdated when checked via /admin outdated endpoint. However schedule update jobs in whose settings.yml this attrib is missing, it always removes addons from the regenerated manifest and thus BOSH reports them as change in manifest thus update jobs always finding these as outdated from schedule update jobs. Fix is simple, add the same param even in schedule update jobs settings.yml.
> Added missing prop service_addon_jobs

- jobs/keepalived/templates/config/keepalived.conf.erb
**Issue:**
Depending on the spec.bootstrap creates a situation in which 10.11.252.11 could be master initially (this ip being bootstrap) and sometimes, 10.11.252.12 could be the master initially (this ip being bootstrap). Thus, this brings in an indeterministic state in which we don't the master node/ip of the broker from outside the VM.
Here, initially refers to a fresh deployment (create) or update deployment of the broker. Here, by default, a node should be master and the other should be slave. Later on, the failover may change the setup.
**Fix:**
We expect the properties, `master_ip` and `slave_ip` to be passed from the sf-manifest. We should then rely on the values of these ips to decide if the VM should be master or slave initially.
> Removing the dependency on spec.bootstrap to fix the master ip for sf-broker

- jobs/service-fabrik-broker/spec
- jobs/service-fabrik-broker/templates/config/settings.yml.erb
* Requirement was to provide capability to optionally enable SSL for external port. 
* Therefore added new property in spec of service-fabrik-broker job and case where property not provided is handled in settings.yml.erb. 
* Tested with openssl client for both positive and negative testcases in broker VM of service-fabrik deployment on boshlite. 
* Also, used same SSL certificate as internal port for testing.
> Adding ssl property for external port

- jobs/iptables-manager/templates/bin/iptables-manager_ctl.erb
ICMP (Ping) and UDP are blocked from other machines from the SF services subnet.
> added rules to block icmp & udp from sf services subnet

- jobs/iptables-manager/templates/bin/iptables-manager_ctl.erb
Reverts cloudfoundry-incubator/service-fabrik-boshrelease#96
Doing this as this is blocking outgoing internet traffic as well.
> Revert "added rules to block icmp & udp from sf services subnet"

- jobs/service-fabrik-scheduler/templates/config/settings.yml.erb
Had missed adding credhub provider config, which is common set of attribs which is injected to each services. With this missing from scheduler config, it resulted in deployments being shown as outdated from update jobs even though they are not really outdated. 
This config ensures we dont fire unnecessary update requests, which results in no-operation in Bosh actually.
> added credhub config to scheduler config

- src/iaas-utils/Godeps/Godeps.json
- src/iaas-utils/Godeps/Readme
- src/iaas-utils/vendor/golang.org/x/oauth2/internal/token.go
- src/iaas-utils/vendor/golang.org/x/oauth2/oauth2.go
- src/iaas-utils/vendor/golang.org/x/oauth2/transport.go
Currently, we use the Godeps (https://github.com/tools/godep) to save the dependencies we require for IaasUtils (package/utility used for HA in GCP) in our boshrelease. As per Godeps, the source-code of the dependency is frozen and the commit-id of the dependency is stored in a file called, `Godeps.json`.
In our case, we felt we didn't need this `Godeps.json`, since the purpose of this file usually is to restore the dependency's code-base to the commit-id specified in the file in the `Gopath`. Since, we never pull the source-code, during our release deployment, we didn't check in the code.
However, we faced issues like, we didn't have any idea, which commit-id the dependency's code referred to. This info is required for getting approvals and/or maintaining the information about the …
> Updating godeps for iaas-utils

- jobs/service-fabrik-backup-manager/templates/config/settings.yml.erb
- jobs/service-fabrik-broker/spec
- jobs/service-fabrik-broker/templates/config/settings.yml.erb
- jobs/service-fabrik-report/templates/config/settings.yml.erb
- jobs/service-fabrik-scheduler/templates/config/settings.yml.erb
This config indicates buffer time in minutes.
Transaction logs ideally should be deleted older than the last successful backup. This buffer time is added to the timestamp (in past) and logs are deleted which are older than that.
e.g. if transaction logs are to be deleted from 15th day, since the 15th day's backup was the last successful backup, then logs older than 15th day + buffer time will be deleted.
> Adding configs for transaction logs delete time buffer

- jobs/service-fabrik-backup-manager/templates/bin/service-fabrik-backup-manager_ctl.erb
- jobs/service-fabrik-bosh-manager/templates/bin/service-fabrik-bosh-manager_ctl.erb
- jobs/service-fabrik-docker-manager/templates/bin/service-fabrik-docker-manager_ctl.erb
- jobs/service-fabrik-virtualhost-manager/templates/bin/service-fabrik-virtualhost-manager_ctl.erb
In this PR only paths are changed.
We can evaluate the consequences of changing job name (logs).
> Rename managers to operators

- jobs/service-fabrik-apiserver/spec
- jobs/service-fabrik-apiserver/templates/config/kubeconfig.erb
The go-client introduced as part of sf-monitoring-agent, needs a default kubeconfig file to connect to API server and fetch metrics.
> Adding Kubeconfig to be used by go-client on sf-monitoring-agent

- config/blobs.yml
- packages/node/spec
Current version of Node v6.9.0 LTS expires 2019 March and we need to upgrade it. Upgrading to latest version 10.13.0 is having an [issue](https://github.com/googleapis/nodejs-compute/issues/216) with gcp node dependency. Hence upgrading it to the intemediate LTS 8.14.0
> upgraded node to v8.14.0

- jobs/service-fabrik-report/templates/config/settings.yml.erb
* With modifications in DbManager init flow to store/fetch credentials from ApiServer (see https://github.com/cloudfoundry-incubator/service-fabrik-broker/pull/468), service-fabrik-report job also needs to communicate to ApiServer, which wasn't the case earlier.  
* Therefore adding required certificates as part of service-fabrik-report job properties.
> Adding apiserver certificates in service-fabrik-report job settings

- jobs/service-fabrik-bosh-manager/templates/config/settings.yml.erb
- jobs/service-fabrik-broker/spec
- jobs/service-fabrik-broker/templates/config/settings.yml.erb
- Include feature flag for allowing sharing of instances
- Include control flag for allowing/disallowing cross-CF organization sharing
> Enable instance sharing on Cloud Foundry

- packages/service-fabrik-deployment-hooks/packaging
package.json file is missed out from copying while creating deployment hooks package from broker. This omit is making the deployments hook compilation to fail on xenial stemcell. This fixes the compilation issue on xenial.
> deployment hooks had missed copying package.json

- jobs/docker/templates/bin/docker_ctl.erb
- jobs/docker/templates/config/syslog_forwarding.conf.erb
- jobs/service-fabrik-backup-manager/templates/bin/service-fabrik-backup-manager_ctl.erb
- jobs/service-fabrik-backup-manager/templates/config/syslog_forwarding.conf.erb
- jobs/service-fabrik-bosh-manager/templates/bin/service-fabrik-bosh-manager_ctl.erb
- jobs/service-fabrik-bosh-manager/templates/config/syslog_forwarding.conf.erb
- jobs/service-fabrik-broker/templates/bin/service-fabrik-broker_ctl.erb
- jobs/service-fabrik-broker/templates/config/syslog_forwarding.conf.erb
- jobs/service-fabrik-docker-manager/templates/bin/service-fabrik-docker-manager_ctl.erb
- jobs/service-fabrik-docker-manager/templates/config/syslog_forwarding.conf.erb
- jobs/service-fabrik-postgresqlmt-operator/templates/bin/pre_start.erb
- jobs/service-fabrik-postgresqlmt-operator/templates/config/syslog_forwarding.conf.erb
- jobs/service-fabrik-report/templates/bin/service-fabrik-report_ctl.erb
- jobs/service-fabrik-report/templates/config/syslog_forwarding.conf.erb
- jobs/service-fabrik-scheduler/templates/bin/service-fabrik-scheduler_ctl.erb
- jobs/service-fabrik-scheduler/templates/config/syslog_forwarding.conf.erb
- jobs/service-fabrik-serviceflow-manager/templates/bin/pre_start.erb
- jobs/service-fabrik-serviceflow-manager/templates/config/syslog_forwarding.conf.erb
- jobs/service-fabrik-virtualhost-manager/templates/bin/service-fabrik-virtualhost-manager_ctl.erb
- jobs/service-fabrik-virtualhost-manager/templates/config/syslog_forwarding.conf.erb
- jobs/swarm_manager/templates/bin/swarm_manager_ctl
- jobs/swarm_manager/templates/config/syslog_forwarding.conf.erb
There is an Issue in the RSyslog-Configuration, where several Jobs deploy a Configuration which imports the module “imtcp”. Since Rsyslog concatenates all configation-Files to one single Configuration, “imtcp” is imported multiple times.
This causes the Rsyslog to produce warnings which are treated as errors by its debug-tool rsyslogd.
```
rsyslogd -N4
rsyslogd: version 8.39.0, config validation run (level 4), master config /etc/rsyslog.conf
rsyslogd: module 'imtcp' already in this config, cannot be added  [v8.39.0 try http://www.rsyslog.com/e/2221 ]
echo $?
1
```
Any deployment which uses Rsyslogd to check its own Configuration will then fail.
This PR will move the “ModLoad”-Commands to one single Configuration file.
- Move `$ModLoad imtcp` to  `10-fabrik_modules.conf`
- Move `$ModLoad …
> Move ModLoads in Rsyslog to one single Configuration-File

- .gitmodules
- config/blobs.yml
- jobs/service-fabrik-apiserver/spec
- jobs/service-fabrik-interoperator/monit
- jobs/service-fabrik-interoperator/spec
- jobs/service-fabrik-interoperator/templates/bin/pre_start.erb
- jobs/service-fabrik-interoperator/templates/config/bpm.yml.erb
- jobs/service-fabrik-interoperator/templates/config/kubeconfig.yaml.erb
- jobs/webhooks/templates/config/webhooks.json.erb
- packages/golang/spec
- packages/interoperator/packaging
- packages/interoperator/pre_packaging
- packages/interoperator/spec
- packages/kubectl/packaging
- packages/kubectl/spec
- packages/service-fabrik-broker/packaging
- packages/service-fabrik-broker/pre_packaging
- packages/service-fabrik-broker/spec
- packages/service-fabrik-deployment-hooks/packaging
- packages/service-fabrik-deployment-hooks/pre_packaging
- packages/service-fabrik-deployment-hooks/spec
* Changed the submodule path of service fabrik broker to facilitate go build of interoperator
* Corresponding path changes done in service fabrik broker and deployment-hooks packages
* Added two new blobs, one for new go1.11.4 version and another for kubectl binary
* Added kubectl package and modified golang package to use 1.11.4 version
* Added interoperator package and job
* modified webhook job's config file to use strict base64 encoding
> Adding service fabrik Interoperator job

- jobs/docker/templates/bin/docker_ctl.erb
- jobs/docker/templates/config/syslog_forwarding.conf.erb
- jobs/service-fabrik-backup-manager/templates/bin/service-fabrik-backup-manager_ctl.erb
- jobs/service-fabrik-backup-manager/templates/config/settings.yml.erb
- jobs/service-fabrik-backup-manager/templates/config/syslog_forwarding.conf.erb
- jobs/service-fabrik-bosh-manager/templates/bin/service-fabrik-bosh-manager_ctl.erb
- jobs/service-fabrik-bosh-manager/templates/config/syslog_forwarding.conf.erb
- jobs/service-fabrik-broker/templates/bin/service-fabrik-broker_ctl.erb
- jobs/service-fabrik-broker/templates/config/syslog_forwarding.conf.erb
- jobs/service-fabrik-docker-manager/templates/bin/service-fabrik-docker-manager_ctl.erb
- jobs/service-fabrik-docker-manager/templates/config/syslog_forwarding.conf.erb
- jobs/service-fabrik-postgresqlmt-operator/templates/bin/pre_start.erb
- jobs/service-fabrik-postgresqlmt-operator/templates/config/settings.yml.erb
- jobs/service-fabrik-postgresqlmt-operator/templates/config/syslog_forwarding.conf.erb
- jobs/service-fabrik-report/templates/bin/service-fabrik-report_ctl.erb
- jobs/service-fabrik-report/templates/config/settings.yml.erb
- jobs/service-fabrik-report/templates/config/syslog_forwarding.conf.erb
- jobs/service-fabrik-scheduler/templates/bin/service-fabrik-scheduler_ctl.erb
- jobs/service-fabrik-scheduler/templates/config/syslog_forwarding.conf.erb
- jobs/service-fabrik-serviceflow-manager/templates/bin/pre_start.erb
- jobs/service-fabrik-serviceflow-manager/templates/config/settings.yml.erb
- jobs/service-fabrik-serviceflow-manager/templates/config/syslog_forwarding.conf.erb
- jobs/service-fabrik-virtualhost-manager/templates/bin/service-fabrik-virtualhost-manager_ctl.erb
- jobs/service-fabrik-virtualhost-manager/templates/config/settings.yml.erb
- jobs/service-fabrik-virtualhost-manager/templates/config/syslog_forwarding.conf.erb
- jobs/swarm_manager/templates/bin/swarm_manager_ctl
- jobs/swarm_manager/templates/config/syslog_forwarding.conf.erb
We are receiving Error-Messages regarding the Service-Fabrik.
```
Could not create tcp listener, ignoring port 514 bind-address (null). [v8.1901.0 try https://www.rsyslog.com/e/2077 ]
```
The syslog configuration currently will attempt to create a TCP-Listener for Port 514. 
https://github.com/cloudfoundry-incubator/service-fabrik-boshrelease/blob/master/jobs/service-fabrik-broker/templates/config/syslog_forwarding.conf.erb#L6
However, this port 514 is located in the privileged area for which higher privileges are needed.
For safety reasons, the new version of Rsyslog will drop the privileges to a standard User. 
See changelog Rsyslog 4.1.1
> Dropping Privileges 
> Starting with 4.1.1, rsyslogd provides the ability to drop privileges by impersonating as another user and/or group after …
> fix Rsyslog-Error 2077

- jobs/service-fabrik-broker/templates/config/settings.yml.erb
Add metering properties to broker job.
This is needed for `runNow` admin endpoint
> Add metering properties

- jobs/keepalived/templates/bin/utils/openstack/generate_token
Resolves #171
Ideally I'd rewrite all these bash scripts in go, but as a hotfix this might be enough.
Even if you have two slashes (e.g. `https://network.my.cloud//v2.0/ports`), it should work.
> Fix NETWORK_PUBLIC_URL detection

- jobs/service-fabrik-scheduler/spec
- jobs/service-fabrik-scheduler/templates/config/settings.yml.erb
* This PR adds configuration for `ArchiveMeteredEvents` job in `service-fabrik-scheduler` bosh job.
* There are two config parameters: `interval` and `events_to_patch`.
> Adding config for ArchiveMeteredEvents job

- jobs/keepalived/templates/bin/notify.sh.erb
- jobs/service-fabrik-broker/templates/bin/health_check.erb
* It is planned to adopt `host` property for specifying IP address in route-registrar properties (refer [here](https://github.com/cloudfoundry/routing-release/pull/111)). With it's usage, it makes sense to perform health check on the the IP given by `host` property instead of obtaining it from underlying VM. This PR makes these changes in health-check script.
> Modifying health check script

- jobs/service-fabrik-backup-manager/templates/config/settings.yml.erb
- jobs/service-fabrik-bosh-manager/templates/config/settings.yml.erb
- jobs/service-fabrik-broker/templates/config/settings.yml.erb
- jobs/service-fabrik-deployment-hooks/templates/config/settings.yml.erb
- jobs/service-fabrik-scheduler/templates/config/settings.yml.erb
- jobs/service-fabrik-virtualhost-manager/templates/config/settings.yml.erb
The service fabrik currently selects the session store and log path based on the broker name. This does not work if the broker has a different name than service-fabrik-broker, because the file permissions are not setup correctly. Also a job should work the store directory with the same name as the job name.
The behavioral change is that
- it is not possible to register the service fabrik under a different name and still use the admin api
- now all store the session into the `/var/vcap/<job>/sessions` instead of the `/var/vcap/service-fabrik-broker/sessions` directory, which also seems to be right (otherwise the service fabrik jobs can't be deployed on different VMs if they use the session store)
> Set session_store and log path based on the job name

- jobs/service-fabrik-backup-manager/templates/config/settings.yml.erb
- jobs/service-fabrik-bosh-manager/templates/config/settings.yml.erb
- jobs/service-fabrik-broker/spec
- jobs/service-fabrik-broker/templates/config/settings.yml.erb
- jobs/service-fabrik-docker-manager/templates/config/settings.yml.erb
- jobs/service-fabrik-report/templates/config/settings.yml.erb
- jobs/service-fabrik-scheduler/templates/config/settings.yml.erb
This adds the setting `riemann.enabled` with the default value `true`, which sets the corresponding setting into the settings.yml file.
This goal of this PR is to add a setting to make Riemann logging optional, i.e. remove the dependency to Riemann (optional instead of required).
The corresponding changes in the broker code: https://github.com/cloudfoundry-incubator/service-fabrik-broker/pull/650
> Add setting riemann.enabled to make Riemann optional

- jobs/service-fabrik-broker/spec
- jobs/webhooks/templates/bin/post-start.erb
* Reverts cloudfoundry-incubator/service-fabrik-boshrelease#178
* Uses a different flag for metering webhook enablement.
> Add meter webhook based on a different flag

- jobs/docker/templates/bin/docker_ctl.erb
* During `monit stop` a connection over unix socket located at `/var/vcap/sys/run/docker/docker.sock` is attempted. We also source `DOCKER_TLS` in `docker_ctl` to be used in `monit start`.
* Due to this bug https://github.com/moby/moby/issues/36535, docker cli attempts an `htttps` connection to above unix socket, which results in skipping the code for graceful shutdowns of containers. 
* This PR applies workaround by explicitly unsetting `DOCKER_TLS` and `DOCKER_TLS_VERIFY` to avoid `https` connection between docker-cli and docker daemon over unix socket.
> Unseting TLS related env variables to allow connections over unix socket

- config/blobs.yml
- packages/node/spec
- packages/service-fabrik-broker/spec
- packages/service-fabrik-deployment-hooks/spec
* Removed old blobs which are no longer required (https://github.com/cloudfoundry-incubator/service-fabrik-boshrelease/pull/200/files)
> Updating node version to 12.15.0

- jobs/docker/spec
- jobs/docker/templates/bin/docker_ctl.erb
- jobs/docker/templates/bin/post-start.erb
To maintain constant ID for docker engines in swarm, method suggested in https://github.com/moby/moby/issues/41443 is used. Also `post-start` hook is added to account for scenarios like scratch landscape setup/new docker vm in cluster.
> adding post-start hook for docker job

- jobs/service-fabrik-apiserver/spec
- jobs/service-fabrik-interoperator/templates/config/cluster.yaml.erb
- jobs/service-fabrik-interoperator/templates/config/kubeconfig.yaml.erb
- jobs/service-fabrik-postgresqlmt-operator/templates/config/kubeconfig.yaml.erb
- jobs/service-fabrik-serviceflow-manager/templates/config/kubeconfig.yaml.erb
- jobs/webhooks/templates/config/kubeconfig.yaml.erb
Use the imported ip address instead of hardcode localhost. This should usually not have a behavioral difference, because the exported ip address is localhost.
In our usecase we want to move/replace the apiserver, so we need to have this configurable.
> Import the apiserver ip address when creating the kubeconfig

- packages/service-fabrik-broker/pre_packaging
- packages/service-fabrik-deployment-hooks/pre_packaging
The new v3.0.0 of Yarn package manager has breaking changes from previous version. The `yarn set version berry` now installs v3.x of Yarn. Fixing Yarn version as v2.4.1 until compatibility issues with v3.0.0 are resolved.
Companion of cloudfoundry-incubator/service-fabrik-broker/pull/1397
Overrides #224
> Fix Yarn version to v2.4.1

- config/blobs.yml
- packages/golang/spec
- packages/interoperator/spec
- packages/webhooks/spec
> update golang to v1.19.1

- config/blobs.yml
- packages/docker/packaging
- packages/docker/spec
Updating docker binary used in service-fabrik-boshrelease. 
We are having issue with docker container creation using old docker binary on jammy stemcell version 1.93
> update docker binary used
